name: 'Release'

on:
  push:
    tags: []

jobs:
  build:
    name: Build 🛠️
    uses: nix-community/nixos-wsl/.github/workflows/main.yml@main
  release:
    needs:
      - build
    name: Create Release 📢
    runs-on: ubuntu-latest
    steps:
      - name: Download tarball 📥
        uses: actions/download-artifact@v3

      - name: Download appx 📥
        uses: actions/download-artifact@v3
        with:
          name: appx

      - name: Rename appx ✏️
        run: mv */*.msixbundle NixOS-WSL.msixbundle

      - name: Generate checksums 🔑
        run: |
          mv tarball-modern/nixos-wsl.tar.gz nixos-wsl.tar.gz
          mv tarball-legacy/nixos-wsl.tar.gz nixos-wsl-legacy.tar.gz
          for x in *.tar.gz NixOS-WSL.msixbundle; do
            sha256sum $x > ${x}.sha256
          done

      - name: Attach to release 📦
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nixos-wsl.tar.gz
            nixos-wsl.tar.gz.sha256
            nixos-wsl-legacy.tar.gz
            nixos-wsl-legacy.tar.gz.sha256
            NixOS-WSL.msixbundle
            NixOS-WSL.msixbundle.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
